image: node:16.14.2

stages:
  - npm
  - build
  - lint

npm:
  stage: npm
  script:
    - npm config set registry ${CI_NPM_REGISTRY}
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

build:
  stage: build
  dependencies:
     - npm
  script:
     - npm run build

lint: 
  stage: lint
  dependencies:
     - npm
  script:
     - npm run lint
