stages:          
  - install
  - build

install-job:     
  stage: install
  script:
    - apt-get update && apt-get upgrade -y && \
    - apt-get install -y nodejs \
    - npm install

build-job:     
  stage: build
  script:
    - npm run build