# Generated by Django 4.1.3 on 2022-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historic_wind',
            fields=[
                ('wind_data_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('msl', models.IntegerField()),
                ('date_val', models.DateTimeField()),
                ('longitude', models.IntegerField()),
                ('u_comp', models.FloatField()),
            ],
        ),
    ]
