# Generated by Django 4.1.3 on 2023-02-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='number_of_turbines',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='operator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='sitename',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='turbine_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
