# Generated by Django 4.1.3 on 2022-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindFarmData',
            fields=[
                ('windfarm_data_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('hub_height', models.IntegerField(default=100)),
                ('number_of_turbines', models.ImageField(blank=True, default=50, upload_to='')),
                ('turbine_capacity', models.FloatField(blank=True)),
                ('is_onshore', models.BooleanField(default=0)),
            ],
        ),
    ]
