# Generated by Django 4.1.3 on 2023-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarEnergyData",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("gsp_id", models.IntegerField()),
                ("datetime_gmt", models.DateTimeField()),
                ("generation_mw", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SolarFarmDetailData",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("operator", models.CharField(max_length=200, null=True)),
                ("sitename", models.CharField(max_length=200, null=True)),
                ("development_status", models.CharField(max_length=200, null=True)),
                (
                    "mounting_type_for_solar",
                    models.CharField(max_length=200, null=True),
                ),
                ("x_coordinate", models.FloatField(blank=True, null=True)),
                ("y_coordinate", models.FloatField(blank=True, null=True)),
                ("address", models.CharField(max_length=200, null=True)),
                ("region", models.CharField(max_length=200, null=True)),
                ("country", models.CharField(max_length=200, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
