# Generated by Django 4.1.3 on 2022-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('forecast_data_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('date_val', models.DateTimeField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('temperature_2m', models.FloatField()),
                ('surface_pressure', models.FloatField()),
                ('winspeed_10m', models.FloatField()),
                ('windspeed_80m', models.FloatField()),
            ],
        ),
    ]
