# Generated by Django 4.1.3 on 2023-02-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='windfarmdetaildata',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='windfarmdetaildata',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='windfarmdetaildata',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
