# Generated by Django 4.1.3 on 2022-11-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicwind',
            name='latitute',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historicwind',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
