# Generated by Django 4.1.3 on 2022-12-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0002_windfarmdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarmdata',
            name='is_onshore',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='windfarmdata',
            name='number_of_turbines',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
