# Generated by Django 4.1.3 on 2023-02-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0002_windfarmdetaildata_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarEnergyData',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('gsp_id', models.IntegerField()),
                ('datetime_gmt', models.DateTimeField()),
                ('generation_mw', models.FloatField()),
            ],
        ),
    ]
