# Generated by Django 4.1.3 on 2023-03-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0002_solarenergydata_solarfarmdetaildata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSPLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsp_id', models.IntegerField(null=True)),
                ('gsp_name', models.CharField(max_length=200, null=True)),
                ('gsp_lat', models.FloatField(blank=True, null=True)),
                ('gsp_lon', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
