# Generated by Django 4.1.3 on 2022-11-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0002_alter_historicwind_latitute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicwind',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
