# Generated by Django 4.1.3 on 2023-02-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0002_alter_windfarmdetaildata_number_of_turbines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='turbine_height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
