# Generated by Django 4.1.3 on 2023-02-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0003_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindFarmDetailData',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('operator', models.CharField(max_length=200)),
                ('sitename', models.CharField(max_length=200)),
                ('is_onshore', models.BooleanField(default=True)),
                ('turbine_height', models.IntegerField(default=100)),
                ('number_of_turbines', models.IntegerField(blank=True, default=50)),
                ('turbine_capacity', models.FloatField(blank=True)),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
