# Generated by Django 4.1.3 on 2023-02-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0003_solarenergydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarFarmDetailData',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('operator', models.CharField(max_length=200, null=True)),
                ('sitename', models.CharField(max_length=200, null=True)),
                ('development_status', models.CharField(max_length=200, null=True)),
                ('mounting_type_for_solar', models.CharField(max_length=200, null=True)),
                ('x_coordinate', models.FloatField(blank=True, null=True)),
                ('y_coordinate', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
