# Generated by Django 4.1.3 on 2023-02-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0003_alter_windfarmdetaildata_turbine_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='number_of_turbines',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
