# Generated by Django 4.1.3 on 2023-01-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend_db", "0004_defaultuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DefaultUser",
        ),
    ]
