# Generated by Django 4.1.3 on 2023-02-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0004_alter_windfarmdetaildata_number_of_turbines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='x_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='y_coordinate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
