# Generated by Django 4.1.3 on 2023-02-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0005_alter_windfarmdetaildata_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windfarmdetaildata',
            name='number_of_turbines',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
