# Generated by Django 4.1.3 on 2023-02-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_db', '0006_alter_windfarmdetaildata_number_of_turbines'),
    ]

    operations = [
        migrations.AddField(
            model_name='windfarmdetaildata',
            name='development_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
